### ISSUE TITLE
promote rascal-vscode to usethesource

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/usethesource.github.io#10]
* Name: rascal-vscode,  but should be renamed to *rascal-language-servers*
* Owner: @jurgenvinju 
* github: https://github.com/cwi-swat/rascal-vscode

## motivation

* we are moving to support the Rascal IDE and generated DSL IDEs via the Language Server Protocol
* this will be the prime way of interacting with Rascal programs and DSL code in different editor/IDE contexts
* currently VScode is only supported, but VScode is a very popular IDE infra-structure that is also the origin of the LSP
* there is no viable alternative
* this project is extensible with other code to plugin the generic LSP into specific IDE clients (emacs, Eclipse, etc.)

## vote

- [x] @PaulKlint 
- [x] @tvdstorm 
- [x] @jurgenvinju 
- [x] @DavyLandman

**Comment by DavyLandman** [comment]
From swat.engineering side we also plan to support this part of the rascal project and see many use cases for it.

**Comment by jurgenvinju** [comment]
@PaulKlint @tvdstorm do you see any arguments against the proposal?

**Comment by jurgenvinju** [comment]
on the (important) TODO list, next to finishing the features:

* some form of (unit) testing the responses from the Rascal LSP server and the DSL LSP server
* some form of testing the terminal support?
* open source LICENSE
* CITATION.md

**Comment by PaulKlint** [comment]
The new name _rascal-language-servers_ is much better, thanks.

**Comment by jurgenvinju** [comment]
The project was first moved and then renamed as planned. Thanks!
