### ISSUE TITLE
rascal on usethesource

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/usethesource.github.io#3]
rascal is a central project on usethesource and it should be there; but let's hold to the process guidelines as in http://usethesource.io/about/processes.html and quickly move rascal through the incubation process to get things started. 

The rascal project includes the following github repositories in the cwi-swat organisation:
- rascal
- rascal-eclipse
- rascal-shell
- rascal-feature
- rascal-update-site
- rascal-pom-master
- rascal-website
- rascal-pom-parent
- rascal-developers-feature
- rascal-eclipse-junit-runner

I propose we let the CLA signing go in parallel with moving the project, as an exception to the process since Rascal is so central and we have all contributed to it knowing it was open-source up-front.

I also propose to fix the problems with file LICENSE's as we go along.

@tvdstorm @PaulKlint please agree.

**Comment by PaulKlint** [comment]
I agree.

**Comment by tvdstorm** [comment]
agree

**Comment by jurgenvinju** [comment]
The code has been moved; CLA's are dropping in asynchronously.
