### ISSUE TITLE
capsule on usethesource

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/usethesource.github.io#4]
capsule by @msteindorfer is the essential library backing the implementation of Rascal's maps, sets and caches. Since it is essential to Rascal I propose we accept it as a usethesource project.

@PaulKlint @tvdstorm please agree. 

@msteindorfer please fill in the CLA here: https://docs.google.com/a/vinju.org/forms/d/1uI6IsuKA-XMPt3jMbtQd9u0pQvDFQ99udbOoiB2La0A/viewform

**Comment by PaulKlint** [comment]
I agree.

**Comment by tvdstorm** [comment]
agree

**Comment by jurgenvinju** [comment]
done
