### ISSUE TITLE
rascal-value on usethesource

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/usethesource.github.io#5]
rascal-value is the central API for data representation for Rascal. As such it is an essential component for usethesource and we should move it there asap.

@PaulKlint @tvdstorm please agree.

Since pdb.values was hosted on Eclipse.org before (and is now forked and split into rascal-value) the co-authors from IBM have signed a CLA with Eclipse before (Robert Fuhrer in particular), which I consider enough evidence of due diligence.

**Comment by PaulKlint** [comment]
I agree.

**Comment by tvdstorm** [comment]
agree

**Comment by jurgenvinju** [comment]
done
