### ISSUE TITLE
impulse on usethesource

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/usethesource.github.io#6]
impulse is the fork of Eclipse IMP for use with Rascal-eclipse and derived IDEs. For as long as we depend on it, it needs to be maintained and for this it should have presence on usethesource. I do suggest that impulse will only remain life on usethesource while we and the IDEs we generate also depend on it, and we make sure to communicate that this is the case on the project's webpage.

As it was Eclipse IMP before, the original authors from IBM have signed off on a CLA and vouched for the open-source licenses therein. An additional CLA is not necessary imho for these contributors from the past.

@tvdstorm @PaulKlint please agree.

**Comment by PaulKlint** [comment]
I agree.

**Comment by tvdstorm** [comment]
agree

**Comment by jurgenvinju** [comment]
done
