### ISSUE TITLE
move https://github.com/cwi-swat/update-site-nexus-link-script to usethesource

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/usethesource.github.io#8]
this is an essential part of the usethesource infrastructure.

**Comment by jurgenvinju** [comment]
votes:

- [x] @jurgenvinju 
- [x] @PaulKlint 
- [x] @tvdstorm 

@DavyLandman is the project's owner.

**Comment by DavyLandman** [comment]
Ok, I agree, I should also rewrite it somewhere, so that it generates composite sites, so rollback works.

Although that's an eclipse specific thing, so maybe delay that a bit..

**Comment by jurgenvinju** [comment]
ok. even with the LSP we'd still have Eclipse plugins to deploy.

**Comment by jurgenvinju** [comment]
Moved to https://github.com/usethesource/update-site-nexus-link-script

**Comment by DavyLandman** [comment]
I'll update the server, as the warning says: https://github.com/usethesource/update-site-nexus-link-script/blob/master/cron-runner ;)

**Comment by DavyLandman** [comment]
my bad, we haven't changed the package name, so all good :)
