### ISSUE TITLE
promote salix to usethesource

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/usethesource.github.io#9]
Salix is becoming stable and it is used by a lot of Rascal projects in research. Let's boost its support-level and horizon by moving Salix to usethesource.

* name: salix
* github: https://github.com/cwi-swat/salix
* project owner: @tvdstorm 

## vote

- [x] @PaulKlint 
- [x] @tvdstorm 
- [x] @jurgenvinju 
- [x] @DavyLandman 

### motivation

Salix is used:
* the IDEs for AlleAlle
* the IDE for Rebel
* the UI of DrAmbiguity

Salix fills a gap:
* we need to be able to code UI directly in Rascal
* it gives natural access to (interactive) data visualizations via its bindings of D3 and google charts, etc. which we also need
* it is and can be extended with bindings to all kinds of HTML5 UI features

Salix is efficient (enough):
* although the protocol is quite chatty and uses HTTP sockets now, it seems usable in most situations
* there is room for improving efficiency by moving to pure TCP or WebSockets by removing the latency of starting HTTP connections for every independent interaction

### strategic considerations

* the salix programming model fuses pure Rascal with the HTML document model; if you know Rascal and if you know HTML then Salix is "easy" and does not require additional documentation
* HTML5 is here to stay and has a large audience
* Salix contributes to the "one-stop-shop" theme for Rascal, as opposed to the alternative model where people write javascript and html separately and make connections via `util::WebServer`

### expected maintenance on the short term
* Salix needs to be included as a library with the Eclipse and VScode IDEs because currently as a deployed library it does not work (this is also an issue of the library story for Rascal in general)
* Salix has an experimental feature for "modules" which can be removed to arrive at a simpler model
* Salix expects an initial HTML file per application which should be changed to Rascal salix code that models that index file to close the abstraction
* Salix should work with an open TCP socket for every app instead of using the HTTP protocol.
* Salix could use a library for one or two of the CSS abstraction libraries (such as `bootstrap.css`)

**Comment by jurgenvinju** [comment]
* @tvdstorm I think you agree, so please vote
* @PaulKlint @DavyLandman please discuss if you have reservations?

**Comment by jurgenvinju** [comment]
@tvdstorm @PaulKlint @DavyLandman please vote positively on this, or explain the reservations otherwise, because I need to move forward with continuous integration and release for salix. If it becomes a usethesource project, then the release story is quite different from if it remains a cwi-swat project.

**Comment by DavyLandman** [comment]
I'm fine with it, we'll still need to take care of update site story of releases.

I hope Tijs will take good care of this project.

**Comment by jurgenvinju** [comment]
My plan is to make sure update sites for clair and salix appear on our usethesource releases, once we can move them to usethesource. At least there will be zip files then. 

The next step to host a (federated) update site with all the plugins is.. well the next step ;-)
